sudo: required
language: go
go:
- 1.11.x
services:
- docker
env:
  global:
  - GO111MODULE=on
cache:
  directories:
  - $GOPATH/pkg/mod
install:
    |
      go mod download
      export PACK_PATH="$PWD/artifacts/pack-${TRAVIS_TAG:-$TRAVIS_BUILD_NUMBER}-${TRAVIS_OS_NAME}"
      if [[ $TRAVIS_OS_NAME = linux ]]; then export CGO_ENABLED=0; fi
      go build -ldflags "-X 'main.Version=$TRAVIS_TAG (git sha: $(git log -1 --pretty=%H))'" -o "$PACK_PATH" ./cmd/pack
      "$PACK_PATH" version
jobs:
  include:
  - name: tests
    os: linux
    script: PACK_TAG=0.0.1-rc.721 go test -count=1 -parallel=1 -v ./... && go test -count=2 -parallel=1 -v -tags=acceptance ./acceptance/...
