language: go
go:
- 1.11.x
os:
- linux
env:
  global:
  - GO111MODULE=on
  - DOCKER_TLS_VERIFY=1
  - secure: HMHLnbmeL7g48nNPUvUOMZJqywBNBXAGwGHSu0CSB9kPcaysnyU4anWmmNR1CCdfbuxDoIT1mdxE+pmE3KsYQew4YGj9qHUdEWoOHdAQn4lC0PbZomTihM117u8If2v4svKcb4itWqxwrEr46Wi1tkzA9vWZl3EjRkj/0IRabIPI5Yj/LgcN+W3stbxBJzEtEaEux/j6WreLag1EdAZTzA/eIDKOIcTIjvyDcSMhRWe6QI60Zcm3AN2smRRllTvS5mK9b8tD/B1J9mU2ddTiZEPMEyMf8hhd0lrbdbdy3i1xyCriK/pfxhjweuU7+Yid1lJ8A9Izqa/RV9Vozx9keSFzSkL5SFGr87Azo/EROTuoUDH+xsGX+pf/vE1hq3SJfSL7GZhPLuW+vyeGPVzqhSShGFv4ZxCcWZL2lILaiTRCYSxonpxGvNJxqLgA/DsA+WRw1gf3nXHTN+ZD7+5uWojQmv/wRMpv5URBQ9wlJufDp07hI4AZuAXpPYgiURrxL391UmWzMvvI3JomdrBLNo9MDNfmPtYrqRI5dZKWorNSr0FNG7iKO6aPF6mbHi2gAhHCMIzKQYGPyKjU7N8J1s4qNnxeukWMsmAQr1dOmj3I93dQwYUVD6hxyFF0McM5qUxo7NmDgo0U5qjcLmGYtvMUZuW91XPWdqwmH9aLGYk=
cache:
  directories:
  - $GOPATH/pkg/mod
before_install:
- openssl aes-256-cbc -K $encrypted_c7ea36ef0bae_key -iv $encrypted_c7ea36ef0bae_iv -in .travis/key.pem.enc -out .travis/key.pem -d
- export DOCKER_CERT_PATH=$PWD/.travis/
install: true
script:
- |
  pack_version="$TRAVIS_TAG (git sha: $(git log -1 --pretty=%H))"
  pack_artifact_version="${TRAVIS_TAG:-$TRAVIS_BUILD_NUMBER}"
  GOOS=linux go build -ldflags "-X 'main.Version=${pack_version}'" -o "artifacts/pack-${pack_artifact_version}-linux" ./cmd/pack
  GOOS=darwin go build -ldflags "-X 'main.Version=${pack_version}'" -o "artifacts/pack-${pack_artifact_version}-darwin" ./cmd/pack
  GOOS=windows go build -ldflags "-X 'main.Version=${pack_version}'" -o "artifacts/pack-${pack_artifact_version}-windows" ./cmd/pack
  "./artifacts/pack-${pack_artifact_version}-linux" version
  PACK_PATH="$PWD/artifacts/pack-${pack_artifact_version}-linux" go test -parallel 1 -v ./...
deploy:
  provider: gcs
  access_key_id: GOOGKYYDLY5ACGLNZVYXGTTN
  secret_access_key:
    secure: pSh3XiGfsLKJSY4WxpAxS4rejfI0CY7JfqBZq6MyrEjzTREzoe0GEsKBqx+E/ext2wFsEda0sl2tLPtle29YXRUC2gb2k1zH9YlQv2XqGPmSzbX++QqXRpm1um4KMSJM95mxXuP9DEkjsQLFPdiR0tK5AZ7pPSu4fbrtEb1Kn98DQknslvyzSzKXASZFRuOOCzWDUu4iKQR64xtOuA9dFz1s0V0+tD7R2USyPYwn2UlABalTt5t1rdm4Tz5vAG91GQq9onMIAzHuiW89t790u5kzBhhLSYSd1Fm5ChcLQhRMZ2rKvFVQHl580CtCkKou5xEEBZZrX5PBmOdAhLkkz389wUfT410DuBoIiUCzK8ioxk4UqPG3SC02v7fct8PIST2f1uT71oVMyKGtWwNEtZ8a4uwdRI37zCDfP3/uaVN5NY5Lg9fCmMNnAyPbg3zf4bVjrpDGN9QgAcpHTnhJj6/9TvT+SQqrnCYzonemq2aCc7d8tCXVcM6JItUV467oSyHIlI7Uro0LGcaYHHAzfbe/tVulruYWEw17XpJ9MX5qNZukWvMDiZP6hqNBGotMS6fS0Qo7qRFgye1oLFVPgHblVG/rYi2qpQ+IKxO4EMprvf0rJDxDUPmMFuig5QZ5c3riIq09Lrm0LAs0RPRnDbkuHFTkUcNhgzff1Jix8U4=
  bucket: pack-cli
  skip_cleanup: true
  acl: public-read
  local-dir: ./artifacts/
  on:
    repo: buildpack/pack
    condition: |
      "$TRAVIS_BRANCH" = master || "$TRAVIS_TAG" != ''
    all_branches: true
after_deploy:
- echo "https://storage.cloud.google.com/pack-cli/pack-${pack_artifact_version}-darwin"
- echo "https://storage.cloud.google.com/pack-cli/pack-${pack_artifact_version}-linux"
- echo "https://storage.cloud.google.com/pack-cli/pack-${pack_artifact_version}-windows"
