sudo: required
language: go
services:
- docker
go:
## Convert to 1.11.x once it is released
- go1.11rc1
env:
  global:
  - GO111MODULE=on
  - TMPDIR=$HOME/mytmp
script:
- echo "MY TMPDIR=$TMPDIR"
- mkdir -p $TMPDIR
- go build ./cmd/pack
- go test -v ./acceptance
