# appveyor.yml
stack: go 1.11
cache:
  - 'C:\Users\appveyor\go\pkg\mod'

environment:
  GO111MODULE: 'on'
  APPVEYOR_CACHE_ENTRY_ZIP_ARGS: '-t7z -m0=lzma -mx=9'
  PACK_PATH: '%APPVEYOR_BUILD_FOLDER%\artifacts\pack-%APPVEYOR_BUILD_NUMBER%-windows.exe'
  DOCKER_CERT_PATH: '%APPVEYOR_BUILD_FOLDER%\.travis'
  DOCKER_TLS_VERIFY: '1'
  DOCKER_HOST:
    secure: mr15I2SOdxk33kgnKOj7MmfH1scjqe4tT2Ptmh7I778=
  file_secret:
    secure: ZBnL/07wnhfIfOVoGN0vm9EN2tMT5u4JkWVLXBosRrc=

artifacts:
  - path: artifacts

before_test:
  - go mod download
  - go build -ldflags "-X main.Version=gitsha:%APPVEYOR_REPO_COMMIT%" -o %PACK_PATH% ./cmd/pack
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt %DOCKER_CERT_PATH%\key.appveyor.pem.enc -out %DOCKER_CERT_PATH%\key.pem -secret %file_secret%

test_script:
  - go test -count=1 -parallel=1 -v ./...

