name: delivery / release-dispatch

on:
  release:
    types:
      - published

jobs:
  release-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch to Docs
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: pack-release
          repository: buildpacks/docs
